// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School_Svr;

namespace School_Svr.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("School_Svr.Persons", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profilename")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.HasIndex("Profilename");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("School_Svr.Profiles", b =>
                {
                    b.Property<string>("Profilename")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("Profilename");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("School_Svr.SchoolContext+Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentID");

                    b.ToTable("Dipartimenti");
                });

            modelBuilder.Entity("School_Svr.SchoolContext+Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Employers");
                });

            modelBuilder.Entity("School_Svr.Persons", b =>
                {
                    b.HasOne("School_Svr.Profiles", "Profile")
                        .WithMany("Persone")
                        .HasForeignKey("Profilename");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("School_Svr.SchoolContext+Employee", b =>
                {
                    b.HasOne("School_Svr.SchoolContext+Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("School_Svr.Profiles", b =>
                {
                    b.Navigation("Persone");
                });

            modelBuilder.Entity("School_Svr.SchoolContext+Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
